wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.19.11
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1752622079
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 14
      - 23
      - 37
      4: 3.10.16
      5: 0.19.11
      8:
      - 5
      13: darwin-arm64
alpha:
  desc: null
  value: 2.025088212788681
