_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
K:
    value: 5
lambda:
    value: 0.1
m:
    value: 50
max_iter:
    value: 200
n_k:
    value: 100
r:
    value: 5
random_state:
    value: 42
sigma:
    value: 0
