wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.19.11
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1752707054
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      - 37
      4: 3.10.16
      5: 0.19.11
      8:
      - 5
      13: darwin-arm64
m:
  desc: null
  value: 50
r:
  desc: null
  value: 5
n_k:
  desc: null
  value: 100
K:
  desc: null
  value: 4
sigma:
  desc: null
  value: 0.0
lambda:
  desc: null
  value: 1.9753834891051
max_iter:
  desc: null
  value: 200
random_state:
  desc: null
  value: 42
alpha:
  desc: null
  value: 1.9753834891051
